---
title: "popdyn-example"
author: "Jenny_Rempel"
date: "3/4/2019"
output: github_document
---

```{r}
library(tidyverse)
```

We want to stimulate a basic population dynamics process. 

missed the first equation

```{r}
x0 <- 10
r <- 1
K <- 100
Tmax <- 100
```

```{r}
f <- function(x, r = 1, K = 100) {
  x + r * x * (1 - x / K)
}
```

```{r}
r = 2
f(20)
  
  Tmax <- 100
  for(t in 1:Tmax){
   
  }
  })
```


```{r}
Tmax <- 100
df <- tibble(x = x0, t = 0)

for(t in 1:Tmax){
  
  x_t <- df[t, "x"][[1]]
  x_t1<- f(x_t, r = 2.1, K= 100)
  
  df <- bind_rows(df, tibble(s = x_t1, t = t))
}

df %>% ggplot(aes(t,x)) + geom_line()
```

```{r}

## Second exploration
Tmax <- 100
df <- tibble(x = x0, t = 0)

for(t in 1:Tmax){
  
  x_t <- df[t, "x"][[1]]
  x_t1<- f(x_t, r = 2.2, K= 100)
  
  df <- bind_rows(df, 
                  tibble(x = x_t1, t = t))
}
df %>% filter(t>80)

df %>% ggplot(aes(t,x)) + geom_line()

```

```{r}

## Second exploration
Tmax <- 100
df <- tibble(x = x0, t = 0)

for(t in 1:Tmax){
  
  x_t <- df[t, "x"][[1]]
  x_t1<- f(x_t, r = 3, K= 100)
  
  df <- bind_rows(df, 
                  tibble(x = x_t1, t = t))
}
df %>% filter(t>80)

df %>% ggplot(aes(t,x)) + geom_line()

```

```{r}
r_values <- seq(1, 3, length.out = 100)
sim_results <- tibble(x = x0, t = 0, r = 1)
sim_results <- tibble(x = x0, t = 0, r = 1)
for (r in r_values){
  
  tmp <- simulate(r)
  tmp$r_value <- r
  
  sim_results <- bind_rows(sim_results,
                           simulate(r) %>% mutate(r_value = r))
}

```

```{r}}
```